### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by PAyeChan** [feixuwu/UEFireBase#4]
Hello there.
When launching on a device has an error.
Error message : 

:app:compileDebugSources
:app:transformClassesWithDexBuilderForDebug
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by feixuwu** [comment]
Hi, I submit some new content, so you can pull the latest content, to see if still have problem.
If you still have problem, please let me know, thanks very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: PAyeChan <notifications@github.com>
发送时间: Wednesday, October 31, 2018 9:22:24 PM
收件人: feixuwu/UEFireBase
抄送: Subscribed
主题: [feixuwu/UEFireBase] Unable to merge dex (#4)


Hello there.
When launching on a device has an error.
Error message :

:app:compileDebugSources
:app:transformClassesWithDexBuilderForDebug
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

  *   What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

  *   Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

  *   Get more help at https://help.gradle.org

―

**Comment by PAyeChan** [comment]
Hi, thank you for your great help. Running with both plugins (UnrealEngine4-EZ-Mobile-Ads and UnrealEngine4-FireBase) in unreal version 4.20 is ok, now.
