### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by PAyeChan** [feixuwu/UEFireBase#5]
Hello there, 

There is another crash error at the launch of the game.
I trace the error log and found this : 

> 1-02 17:08:01.852 10438-10438/? D/UE4: AdMob:Ready Create!
> 11-02 17:08:01.852 10438-10438/? D/AdCollection:AdMob: Admob:Init
> 11-02 17:08:01.858 10438-10438/? D/AdCollection: queryurl:adplatform=AdMob&packageName=com.paccap.GoldenGlory&os=Android
> 11-02 17:08:01.859 10438-10438/? D/UE4: AdMob:InitFinish:ca-app-pub-1984335862642918~8344734006 ca-app-pub-1984335862642918/3572008188 ca-app-pub-1984335862642918/9494164145 ca-app-pub-1984335862642918/7165607604
> 11-02 17:08:01.860 10438-10438/? D/UE4: FirebaseTest : **Before FirebaseApp.initializeApp**
> 11-02 17:08:01.860 10438-10438/? D/UE4: FirebaseTest : **After FirebaseApp.initializeApp**
> 11-02 17:08:01.881 10438-10438/? D/AndroidRuntime: Shutting down VM
>                                                    
>                                                    
>                                                    --------- beginning of crash

> 11-02 17:08:01.884 10438-10438/? E/AndroidRuntime: FATAL EXCEPTION: MainThread-UE4
>                                                    Process: com.paccap.GoldenGlory, PID: 10438
>                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paccap.GoldenGlory/com.epicgames.ue4.GameActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.paccap.GoldenGlory. Make sure to call FirebaseApp.initializeApp(Context) first.
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2854)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929)
>                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
>                                                        at android.os.Looper.loop(Looper.java:164)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:6696)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
>                                                     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.paccap.GoldenGlory. Make sure to call FirebaseApp.initializeApp(Context) first.
>                                                        at com.google.firebase.FirebaseApp.getInstance(Unknown Source:59)
>                                                        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
>                                                        at com.util.firebasehelper.FacebookLogin.Init(**FacebookLogin.java:63**)
>                                                        at com.epicgames.ue4.GameActivity.onCreate(**GameActivity.java:1909**)
>                                                        at android.app.Activity.performCreate(Activity.java:7040)
>                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2807)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929) 
>                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618) 
>                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
>                                                        at android.os.Looper.loop(Looper.java:164) 
>                                                        at android.app.ActivityThread.main(ActivityThread.java:6696) 
>                                                        at java.lang.reflect.Method.invoke(Native Method) 
>                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

I open GameActivity.java and found the source of error. This is the "GameActivity" code :

    	Log.debug("FirebaseTest : Before FirebaseApp.initializeApp");
	FirebaseApp.initializeApp(this);
	Log.debug("FirebaseTest : After FirebaseApp.initializeApp"); <-- this code works, the log shows the message

        try
        {
              final String googleClientID = _bundle.getString("com.epicgames.ue4.firebase.googleclientid");
              mGoogleLogin = new GoogleLogin(this, googleClientID);
        }
        catch(Exception e)
        {

        }
             
        mFacebookLogin = new FacebookLogin(this);
        if(!mFacebookLogin.Init(BuildConfiguration) )  <--- this is line 1909 in my GameAcivity file
        {
             mFacebookLogin = null;
             Log.error("Facebook SDK failed to initialize!");
	}

I am sorry, I decompile your **firebasehelper** library. And I found the error occurs inside this function : 

> public boolean Init(String BuildConfiguration)
>   {
>     this.mAuth = FirebaseAuth.getInstance(); <-- error log points to this line

Can you fix the error, please
thanks

**Comment by feixuwu** [comment]
please check my firebase demo project, u need first call firebase initlize
.
?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
sorry, from the code, I did not found error, did you use the right config for firebase?
you can read the code from my demo project, maybe u can find the problem.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PAyeChan** [comment]
yeah, in a blank project, there is no error. I follow your demo project and configs are right.
I am gonna try with only one plugin after cleaning the whole project.

**Comment by PAyeChan** [comment]
Did you test with both plugins(**EZ-Mobile-Ads** and **UEFirebase**) ?
Is everything ok ?

**Comment by feixuwu** [comment]
I will check it next morning

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PAyeChan** [comment]
Ohh, it works now.
Thank you so much for your help.
